/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jnidemo_cn_example_com_jnidemo_MainActivity */

#ifndef _Included_jnidemo_cn_example_com_jnidemo_MainActivity
#define _Included_jnidemo_cn_example_com_jnidemo_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jnidemo_cn_example_com_jnidemo_MainActivity
 * Method:    getString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jnidemo_cn_example_com_jnidemo_MainActivity_getString
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
